CREATE TABLE IF NOT EXISTS tenant (
    tenant_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    public_key VARCHAR(255) NOT NULL UNIQUE,
    private_key VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    attached_plan VARCHAR(50),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 